apps/subitem/urls.py
from django.urls import path

from .views import CreateSubItem, UpdateSubItem, ListSubItem
app_name='subitem'
urlpatterns = [
    # create views
    path('add', CreateSubItem.as_view() ,name='add'),
    # update views
    path('update', UpdateSubItem.as_view() ,name='update'),
    # list views
    #path('processes', ListProcesses.as_view() , name="list-processes"),
    path('', ListSubItem.as_view() ,name='list'),
    #path('subserviceorders', ListSubServiceOrders.as_view() ,name='list-subserviceorders'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    # ADD NEW Routes HERE
    path("serviceorders/", include("apps.serviceorder.urls") , name="serviceorder"),
    path("subserviceorder/", include("apps.subserviceorder.urls") , name="subserviceorder"),
    path("item/", include("apps.item.urls") , name="item"),
    path("subitem/", include("apps.subitem.urls") , name="subitem"),
    path("process/", include("apps.process.urls") , name="process"),
    path("employee/", include("apps.employee.urls"), name="employee" ),
    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls")),
    
    path("", include("apps.inprocesses.urls"))
]

apps/serviceordercontrol/models.py
#from django.db import models

# Create your models here.



# Create your models here.

# -*- encoding: utf-8 -*-

from django.db import models
from django.urls import reverse
from apps.authentication.models import *
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from localflavor.br.models import BRCPFField, BRCNPJField, BRPostalCodeField, BRStateField
from simple_history.models import HistoricalRecords
from django.utils.timezone import now
import datetime as datetime2
from django.core.mail import send_mail

class ServiceOrder(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    #sub_os = models.ManyToOneRel(to=SubServiceOrder,on_delete=models.DO_NOTHING)
    number =  models.IntegerField()

    def __str__(self):
        return self.number

    def save(self, *args, **kwargs):
        if self._state.adding:
            # Get the maximum display_id value from the database
            last_number = self.objects.all().aggregate(largest=models.Max('number'))['largest']

            # aggregate can return None! Check it first.
            # If it isn't none, just use the last ID specified (which should be the greatest) and add one to it
            if last_number is not None:
                self.number = last_number + 1

        super(ServiceOrder, self).save(*args, **kwargs)


class Client(models.Model):
    name = models.CharField(verbose_name="Nome", max_length=512, blank=True)
    company_id = BRCNPJField(verbose_name="CNPJ", max_length=512, blank=True)
    

class SubServiceOrder(models.Model):
    main_os = models.ForeignKey(ServiceOrder, on_delete=models.CASCADE)
    number = models.IntegerField()
    client = models.ForeignKey(Client, on_delete=models.DO_NOTHING)
    def save(self, *args, **kwargs):
        if self._state.adding:
            # Get the maximum display_id value from the database
            last_number = self.objects.all().aggregate(largest=models.Max('number'))['largest']

            # aggregate can return None! Check it first.
            # If it isn't none, just use the last ID specified (which should be the greatest) and add one to it
            if last_number is not None:
                self.number = last_number + 1
        super(SubServiceOrder, self).save(*args, **kwargs)

class Process(models.Model):
    name = models.CharField(verbose_name="Nome", max_length=512, blank=True)


class ServiceOrderHistory(models.Model):
    
    
    process = models.ForeignKey(Process, null=True, verbose_name=_("Processo"), on_delete=models.SET_NULL,  related_name="idProcess")
    os = models.ForeignKey(SubServiceOrder, null=True, verbose_name=_("Ordem de Serviço"), on_delete=models.SET_NULL, related_name="idServiceOrder")
    employee = models.ForeignKey(Employee, null=True, verbose_name=_("Colaborador"), on_delete=models.SET_NULL, related_name="idEmployee")
    start = models.TimeField(_("Início"), auto_now_add=True)
    end =  models.TimeField(_("Fim"), null=True, blank=True,auto_now=False, auto_now_add=False)
    incidents = models.TextField(_("Ocorrências"),null=True, blank=True)
    period = models.IntegerField(_("Periodo de tempo"),null=True,blank=True, default=1)
    date = models.DateTimeField( default=now, null=True, blank=True)
    qtd = models.IntegerField(null=True, blank=True, default=1)
    history = HistoricalRecords()
    def __str__(self):
        
        return f"O.S: {self.os.Numero_Os} - {self.processo} - {self.qtd}"
    
    class Meta:
        #db_table = 'Historico_os'
        ordering = ['-end']
        verbose_name = _("Localização O.S")
        verbose_name_plural = _("Localizar O.S")

    def time(self):
        try:
            enter_delta = datetime2.timedelta(hours=self.inicio.hour, minutes=self.inicio.minute, seconds=self.inicio.second)
            exit_delta = datetime2.timedelta(hours=self.fim.hour, minutes=self.fim.minute, seconds=self.fim.second)
            difference_delta = exit_delta - enter_delta
            return difference_delta
        except:
            return 'Não Finalizado'
    def avg_qtd(self):
        try:
            result_hour, plural_hour= None, None
            result =  self.time().total_seconds()/self.qtd/60
            plural = 'minutos' if round(result, 2) > 1 else 'minuto'
            if round(result, 2) >= 60:
                result_hour = round(round(result, 2)/60,2) 
                plural_hour = 'hora(s)'
                plural = plural+' / '
            return f'{round(result, 2)} {plural} {result_hour or ""} {plural_hour or ""}'
        except Exception as e:
            print(e)
            return 'Não Finalizado'
    def date_obj(self):
        try:
            return f'{self.data.day}/{self.data.month}/{self.data.year}'
        except:
            return 'Data não encontrada.'

   
    
    def save(self, *args, **kwargs):
        try:
            lperiod = ServiceOrderHistory.objects.values('period').filter(os=self.os).latest('period')
            lperiod = lperiod['period'] + 1
        except:
            lperiod = 1
        
        self.periodo = lperiod
        super().save(*args, **kwargs)
        domain = 'https://admin.peppertools.com.br'
        info = (self._meta.app_label, self._meta.model_name)
        info_os = (self.os._meta.app_label, self.os._meta.model_name)
        os_url = '\nVeja a Ordem de Serviço em '+ domain + reverse('admin:%s_%s_change' % info_os, args=(self.os.pk,))  
        admin_url = '\nVeja em '+ domain + reverse('admin:%s_%s_change' % info, args=(self.pk,))  
        SubServiceOrder.objects.filter(pk=self.os.id).update(STATUS=self.processo.procname)
        tempo_por_peca = '\nTempo por peça '+str(self.avg_qtd()) if self.fim else ''
        print(tempo_por_peca) 
        tempo = 'iniciada' if not self.fim else 'finalizada'
        subject = 'Ordem de Serviço N. '+ str(self.os.Numero_Os) +' '+tempo+' por '+ self.colaborador.username +' em '+self.processo.procname       
        message = 'Ordem de Serviço '+tempo+' por '+ self.colaborador.username +' em '+self.processo.procname+tempo_por_peca +' '+ admin_url + os_url
        from_email = 'contato@peppertools.com.br'
        send_mail(subject, message, from_email, ['contato@peppertools.com.br'], fail_silently=False)
        
        

apps/subitem/models.py
from django.db import models

from apps.authentication.models import Company
from apps.item.models import Item

# Create your models here.
class SubItem(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    main_item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1, editable=True)
    number = models.IntegerField(default=1, editable=False)
    name = models.CharField(verbose_name="Nome", max_length=512, blank=False)
    description = models.CharField(verbose_name="Descrição", max_length=512, blank=False)

    def save(self, *args, **kwargs):
        if self._state.adding:
            # company = Company.objects.get(user=self.request.user)
            # self.company = company
            # Get the maximum display_id value from the database
            last_number = SubItem.objects.all().aggregate(largest=models.Max('number'))['largest']

            # aggregate can return None! Check it first.
            # If it isn't none, just use the last ID specified (which should be the greatest) and add one to it
            if last_number is not None:
                self.number = last_number + 1
        super().save(*args, **kwargs)

apps/subitem/forms.py
from dataclasses import field
from pyexpat import model
from django import forms

from apps.item.models import Item
from .models import SubItem
from ..subserviceorder.models import SubServiceOrder
from ..forms_addons import CompanyAddonForm

# CompanyAddonForm extends forms.Models

class SubItemForm(CompanyAddonForm):

    
    
    def __init__(self, *args, **kwargs):
        
        self.request = kwargs.pop("request")
        self.item_id = kwargs.pop('item_id','')
        self.get_company()
        super(SubItemForm, self).__init__(*args, **kwargs)
        self.fields['main_item'] = forms.ModelChoiceField( empty_label='Selecione um Item Matriz', label='Item', queryset=Item.objects.filter(company=self.company))
    class Meta: 
        model = SubItem
        fields = ['name', 'description', 'quantity']

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.company = self.company
        instance.save()
        # for i in instance.subserviceorders:
        #     so = SubServiceOrder.objects.get(pk=i.id)
        #     so.mainos = instance
        #     so.save()
    

apps/subitem/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from django.views.generic.list import ListView
from .forms import SubItemForm
#from .permissions import EmployeePermission
from apps.serviceorder.models import *
# Create your views here.
from apps.views_addons import CompanyAddonListView, CompanyAddonUpdateView, CompanyAddonCreateView




class CreateSubItem(CompanyAddonCreateView):
    form_class = SubItemForm
    template_name = 'serviceordercontrol/subitem/add-subitem.html'

    def get_context_data(self, **kwargs):
        kwargs['segment'] = 'SubItem'
        return super().get_context_data(**kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

class UpdateSubItem(CompanyAddonUpdateView):
    form_class = SubItemForm
    template_name = 'serviceordercontrol/subitem/update-subitem.html'

    def get_context_data(self, **kwargs):
        kwargs['segment'] = 'SubItem'
        return super().get_context_data(**kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs
    
class ListSubItem(CompanyAddonListView):
    paginate_by = 10
    ordering = ['name']
    model = ServiceOrder
    template_name = 'serviceordercontrol/subitem/list-subitem.html'
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_context_data(self, **kwargs):
        kwargs['segment'] = 'SubItem'
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.get_company() 
        return ServiceOrder.objects.filter(company=self.company)

apps/templates/serviceordercontrol/subitem/add-subitem.html
{% extends "layouts/base.html" %}
{% load widget_tweaks %}
{% block title %} Item {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Sub Item</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="javascript:">Sub Item</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <div class="main-body">
                <div class="page-wrapper">
                    <!-- [ Main Content ] start -->
                    <div class="row">
                        <div class="col-sm-12">
                          <form action="{% url 'subitem:add' %}" method="post">
                            {% csrf_token %}  
                    {% for field in form.visible_fields %}

                            <div class="input-group mb-4">
                            
                            {% render_field field class="form-control" placeholder=field.label %}
                            </div>
                                {% for error in field.errors %}
                                    <span class="text-error" >{{ error }}</span>
                                {% endfor %}
                      
                   
                    {% endfor %}
                    <button type="submit btn btn-primary">Salvar</button>
                </form>  


                        </div>
                    </div>
                    <!-- [ Main Content ] end -->
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/serviceordercontrol/subitem/list-subitem.html
{% extends "layouts/base.html" %}

{% block title %} Item {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Sub Item</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="javascript:">Sub Item</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <div class="main-body">
                <div class="page-wrapper">
                    <div class="row">
                        <div class="col-md-6 col-xl-4">

                            <a href="{% url 'subitem:add' %}"> <button type="button" class="btn btn-primary" title="" data-toggle="tooltip" data-original-title="Adicionar Sub Item">Adicionar Sub Item</button></a>
                       
                       </div>
                    </div>
                    <!-- [ Main Content ] start -->
                    <div class="row">
                        <!-- <div class="col-md-6 col-xl-4">

                            <div class="card">
                                <div class="card-header">
                                    <h5>Hello card</h5>
                                </div>
                                <div class="card-block">
                                    <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                    </p>
                                </div>
                            </div>
                        </div> -->
                    {% for object in page_obj %}

                    <div class="col-md-6 col-xl-4">

                        <div class="card">
                            <div class="card-header">
                                <h5>{{ object.name }} </h5>
                            </div>
                            <div class="card-block">
                                <p>
                                </p>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                        <!-- <div class="col-md-6 col-xl-4">

                            <div class="card">
                                <div class="card-header">
                                    <h5>Hello card</h5>
                                </div>
                                <div class="card-block">
                                    <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                    </p>
                                </div>
                            </div>
                        </div> -->
                        

                        <!-- <div class="col-md-6 col-xl-4">

                            <div class="card">
                                <div class="card-header">
                                    <h5>Hello card</h5>
                                </div>
                                <div class="card-block">
                                    <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                    </p>
                                </div>
                            </div>
                        </div> -->

                        <!-- <div class="col-md-6 col-xl-4">

                            <div class="card">
                                <div class="card-header">
                                    <h5>Hello card</h5>
                                </div>
                                <div class="card-block">
                                    <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                    </p>
                                </div>
                            </div>
                        </div> -->

                        <!-- <div class="col-md-6 col-xl-4">

                            <div class="card">
                                <div class="card-header">
                                    <h5>Hello card</h5>
                                </div>
                                <div class="card-block">
                                    <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                    </p>
                                </div>
                            </div>
                        </div> -->

                        <!-- <div class="col-md-6 col-xl-4">

                            <div class="card">
                                <div class="card-header">
                                    <h5>Hello card</h5>
                                </div>
                                <div class="card-block">
                                    <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                    </p>
                                </div>
                            </div>
                        </div> -->

                         <!-- <div class="col-md-6 col-xl-4">

                            <div class="card">
                                <div class="card-header">
                                    <h5>Hello card</h5>
                                </div>
                                <div class="card-block">
                                    <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                    </p>
                                </div>
                            </div>
                        </div> -->
                        
                        </div>
                    </div>
                    <!-- [ Main Content ] end -->
                </div>
            </div>
        </div>

        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                {% endif %}
                {% for i in page_obj.paginator.num_pages|get_range %}
                    
                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
    
    
                {% endif %}
                
            </ul>
        </nav>

    </div>
  
    



{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/serviceordercontrol/subitem/update-subitem.html
{% extends "layouts/base.html" %}
{% load widget_tweaks %}
{% block title %} Item {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Sub Item</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'subitem:list' %}">Sub Item<i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="javascript:">Change</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <div class="main-body">
                <div class="page-wrapper">
                    <!-- [ Main Content ] start -->
                    <div class="row">
                        <div class="col-sm-12">
                            <form action="{% url 'subitem:update' %}" method="post">
                                {% csrf_token %}  
                            {% for field in form.visible_fields %}

                            <div class="input-group mb-4">
                            
                            {% render_field field class="form-control" placeholder=field.label %}
                            </div>
                                {% for error in field.errors %}
                                    <span class="text-error" >{{ error }}</span>
                                {% endfor %}
                      
                   
                            {% endfor %}
                            <button type="submit btn btn-primary">Salvar</button>
                            </form>

                        </div>
                    </div>
                    <!-- [ Main Content ] end -->
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}