apps/employee/urls.py
from .views import ListEmployees
from django.urls import path
app_name='employee'
urlpatterns = [
path('', ListEmployees.as_view(), name='list'),
]

apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views
app_name='home'
urlpatterns = [

    # The home page
    path('', views.index, name='home'),
    
    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]

apps/item/urls.py
from django.urls import path
from .views import CreateItem, UpdateItem, ListItem
app_name='item'
urlpatterns = [
    # create views
    path('add', CreateItem.as_view() ,name='add'),
    # update views
    path('update/<int:pk>', UpdateItem.as_view() ,name='update'),
    # list views
    path('', ListItem.as_view() , name="list"),
    

]

apps/subitem/urls.py
from django.urls import path

from .views import CreateSubItem, UpdateSubItem, ListSubItem
app_name='subitem'
urlpatterns = [
    # create views
    path('add', CreateSubItem.as_view() ,name='add'),
    # update views
    path('update', UpdateSubItem.as_view() ,name='update'),
    # list views
    #path('processes', ListProcesses.as_view() , name="list-processes"),
    path('', ListSubItem.as_view() ,name='list'),
    #path('subserviceorders', ListSubServiceOrders.as_view() ,name='list-subserviceorders'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    # ADD NEW Routes HERE
    path("serviceorders/", include("apps.serviceorder.urls") , name="serviceorder"),
    path("subserviceorder/", include("apps.subserviceorder.urls") , name="subserviceorder"),
    path("item/", include("apps.item.urls") , name="item"),
    path("subitem/", include("apps.subitem.urls") , name="subitem"),
    path("process/", include("apps.process.urls") , name="process"),
    path("employee/", include("apps.employee.urls"), name="employee" ),
    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls")),
    
    path("", include("apps.inprocesses.urls"))
]

apps/templates/includes/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

apps/templates/includes/navigation.html
<!-- NOT IMPLEMENTED -->

apps/templates/includes/scripts.html
    <!-- Required Js -->
    <script src="{{ ASSETS_ROOT }}/js/vendor-all.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/pcoded.min.js"></script>
<script>
    function formatcpf(i){
   
   var v = i.value;
   
   if(isNaN(v[v.length-1])){ // impede entrar outro caractere que não seja número
      i.value = v.substring(0, v.length-1);
      return;
   }
   
   i.setAttribute("maxlength", "14");
   if (v.length == 3 || v.length == 7) i.value += ".";
   if (v.length == 11) i.value += "-";

}
</script>

apps/templates/includes/sidebar.html
    <nav class="pcoded-navbar">
        <div class="navbar-wrapper">
            <div class="navbar-brand header-logo">
                <a
                   href="{% url 'home:home' %}" class="b-brand">
                    <div class="b-bg">
                        <i class="feather icon-trending-up"></i>
                    </div>
                    <span class="b-title">InProcesses</span>
                </a>
                <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
            </div>
            <div class="navbar-content scroll-div">
                <ul class="nav pcoded-inner-navbar">
                    <li class="nav-item pcoded-menu-caption">
                        <label>Navegação</label>
                    </li>
                    {{segment}}
                    {% if user.is_company or user.is_superuser %}
                    <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                        class="nav-item {% if 'index' in segment %} active {% endif %}">
                        <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Principal</span></a>
                    </li>
                  
                    <li data-username="Employees" 
                        class="nav-item {% if 'employee' in segment %} active {% endif %}">
                        <a href="{%url 'employee:list' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">Employees</span></a>
                    </li>
                    {% endif %}
                    
                    {% if user.is_employee or user.is_superuser %}

                    

                    <li data-username="Employee dashboard" 
                        class="nav-item {% if 'employee-dashboard' in segment %} active {% endif %}">
                        <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Principal</span></a>
                    </li>
                    {% endif %}
                    <!-- block both have permissions  -->
                    <li data-username="Service-Orders" 
                        class="nav-item {% if 'serviceorder' in segment %} active {% endif %}">
                        <a href="{%url 'serviceorder:list' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">Service Orders</span></a>
                    </li>

                    <li data-username="Sub-Service-Orders" 
                        class="nav-item {% if 'sub-service-order' in segment %} active {% endif %}">
                        <a href="{%url 'subserviceorder:list' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext"> Sub Service Orders</span></a>
                    </li>

                    <li data-username="items" 
                        class="nav-item {% if 'item' in segment %} active {% endif %}">
                        <a href="{%url 'item:list' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">Item</span></a>
                    </li>

                    <li data-username="SubItem" 
                        class="nav-item {% if 'SubItem' in segment %} active {% endif %}">
                        <a href="{%url 'subitem:list' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">SubItem</span></a>
                    </li>
                    <!-- endblock both have permissions  -->
                    <li class="nav-item pcoded-menu-caption">
                        <label>UI Element</label>
                    </li>
                    <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds" class="nav-item pcoded-hasmenu">
                        <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-box"></i></span><span class="pcoded-mtext">Components</span></a>
                        <ul class="pcoded-submenu">
                            <li class=""><a href="/ui-button.html" class="">Button</a></li>
                            <li class=""><a href="/ui-badges.html" class="">Badges</a></li>
                            <li class=""><a href="/ui-breadcrumb-pagination.html" class="">Breadcrumb & paggination</a></li>
                            <li class=""><a href="/ui-collapse.html" class="">Collapse</a></li>
                            <li class=""><a href="/ui-tabs.html" class="">Tabs & pills</a></li>
                            <li class=""><a href="/ui-typography.html" class="">Typography</a></li>
                            <li class=""><a href="/ui-icons.html" class="">Feather<span class="pcoded-badge label label-danger">NEW</span></a></li>
                        </ul>
                    </li>
                    <!-- <li class="nav-item pcoded-menu-caption">
                        <label>Forms & table</label>
                    </li> -->
                    <li data-username="form elements advance componant validation masking wizard picker select" 
                        class="nav-item {% if 'ui-forms' in segment %} active {% endif %}">
                        <a href="/ui-forms.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-file-text"></i></span><span class="pcoded-mtext">Form elements</span></a>
                    </li>
                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
                        <a href="/ui-tables.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Table</span></a>
                    </li>
                    <!-- <li class="nav-item pcoded-menu-caption">
                        <label>Chart & Maps</label>
                    </li>
                    <li data-username="Charts Morris" 
                        class="nav-item {% if 'charts-morris' in segment %} active {% endif %}">
                        <a href="/charts-morris.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a></li>
                    <li data-username="Maps Google" 
                         class="nav-item {% if 'maps-google' in segment %} active {% endif %}">
                        <a href="/maps-google.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-map"></i></span><span class="pcoded-mtext">Maps</span></a></li>
                    <li class="nav-item pcoded-menu-caption">
                        <label>Pages</label>
                    </li> -->
                    <!-- <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe" class="nav-item pcoded-hasmenu">
                        <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span class="pcoded-mtext">Authentication</span></a>
                        <ul class="pcoded-submenu">
                            <li class=""><a href="accounts/reset/auth-reset-pass.html" class="">Reset Pass</a></li>
                            <li class=""><a href="/login.html" class="">Login (template)</a></li>
                            <li class=""><a href="/register.html" class="">Register (template)</a></li>
                        </ul>
                    </li> -->
                    <li data-username="Sample Page" 
                        class="nav-item {% if 'page-blank' in segment %} active {% endif %}">
                        <a href="/page-blank.html" class="nav-link"><span class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a></li>
                    <li data-username="Sample Page" class="nav-item"><a href="/page-404.html" class="nav-link"><span class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Error 404</span></a></li>

                    <li data-username="Disabled Menu" class="nav-item">
                        <a href="{% url 'authentication:logout' %}" class="nav-link">
                            <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Logout</span>
                        </a>
                    </li>
                    <!-- <li class="nav-item pcoded-menu-caption">
                        <label>More Resources</label>
                    </li>                     -->
                    <!-- <li data-username="Support Page" class="nav-item ">
                        <a target="_blank" href="https://appseed.us/support" class="nav-link">
                            <span class="pcoded-micon">
                                <i class="feather icon-headphones"></i>
                            </span>
                            <span class="pcoded-mtext">Support</span>
                        </a>
                    </li> -->
                    <!-- <li data-username="Support Page" class="nav-item ">
                        <a target="_blank" href="https://appseed.us/admin-dashboards/django-dashboard-dattaable-pro" class="nav-link">
                            <span class="pcoded-micon">
                                <i class="feather icon-tag"></i>
                            </span>
                           
                        </a>
                    </li>                      -->
                </ul>
            </div>
        </div>
    </nav>